### ISSUE TITLE
Add ability to export secrets

### ISSUE THREAD

**Issue by ascpial** [sparrowcode/otp-auth-ios-app#3]
It might be helpful sometimes to export totp secrets (for example to make a backup on an offline device, or to migrate the secrets on another device).

In other apps, you can show the QR code of the totp token by swiping the code to the right (swiping to the left deletes the code).

Is it possible to implement such a feature in this app?
This app is one of the best I found which is open source, but for me it lacks the ability to export the passwords.

**Comment by ivanvorobei** [comment]
Happy to do it! Great idea

**Comment by ivanvorobei** [comment]
@ascpial 
<img width="1161" alt="Screenshot 2023-01-24 at 13 51 27" src="https://user-images.githubusercontent.com/10995774/214273115-f49e04ea-d7ec-4093-b18d-3390a84e9902.png">

**Comment by ivanvorobei** [comment]
will available with next version in appstore.

**Comment by ascpial** [comment]
Thanks you very much for your work!
