### ISSUE TITLE
Crash when scanning QRCode

### ISSUE THREAD

**Issue by ascpial** [sparrowcode/otp-auth-ios-app#7]
I tried to import a QR code from an other application (Argus), by taking a screenshot and sending it to my PC.
When scanning the QRCode, the app crashes. After that, it's impossible to access the app, because the app crashes when launching.
I tried uninstalling the app entirely but the app still crashes in loop.

This is the image I used. (the secret is now invalid, I'm not sharing sensitive information)

> **Warning**
> Be aware that your data could become inaccessible after scanning the code, don't scan the code if you don't have a backup of your secrets.

<details>
<summary> The QR Code</summary>

![image](https://user-images.githubusercontent.com/72463129/214678939-77037697-29ba-4bd6-a8c0-ce6ae230da68.png)
</details>

**Comment by ivanvorobei** [comment]
Thanks for report! Checking

**Comment by ivanvorobei** [comment]
Bug founded. New version upload to App Store and waiting review. Hope tomorrow it will release. Thanks for your report!

**Comment by ascpial** [comment]
I can confirm that the issue is now resolved on my side!

This update also seems to resolve an issue I had before the crash, where deleting codes did nothing.

Thanks for your work!
