### ISSUE TITLE
Copy is broken

### ISSUE THREAD

**Issue by ascpial** [sparrowcode/otp-auth-ios-app#8]
When copying something a code, the app shows the "Copied" toaster but nothing is copied and the code is not usable in other applications.

**Comment by ivanvorobei** [comment]
Confirmed. Fixing...

**Comment by ivanvorobei** [comment]
Fixed in `2.5.1`. Have sent to Apple.

**Comment by ascpial** [comment]
Thanks for the fix!

**Comment by ivanvorobei** [comment]
@ascpial got some bugs more, new version have sent today.

**Comment by ascpial** [comment]
Thanks!
